### ISSUE TITLE
Unable to save edits in Easton (Release Server) 

### ISSUE THREAD

**Issue by mmcfarland** [OpenTreeMap/otm-android#193]
On the release server configured app:
* Assign Editor role to your user
* Select the Easton Map
* Select any tree
* Edit any number of attributes on tree, hit Save
* "Cannot Edit Tree"

@jwalgran was able to edit a tree in the same scenario with the iPhone app, so it's not likely a backend issue.  However, this _only_ appears to happen for the Easton map,  TreeMapLA instance worked.

**Comment by maurizi** [comment]
@hadleystein1 @jmorrison1847 I recall y'all talking about an issue like this with that a customer had encountered recently.  Any insight or more information y'all might be able to provide?

**Comment by hadleystein1** [comment]
@maurizi I am not familiar with the issue. This may be due to the additional 'geom' 'id' and 'Read Only' type fields listed on the Roles page, that map owners often make Invisible since they do not understand them. @jmorrison1847 any insight?

**Comment by jmorrison1847** [comment]
Great idea @hadleystein1. Any time we see a behavior where someone _should_ be able to make and edit and they can't, it's usually a problem with their permissions on a seemingly unrelated field.

**Comment by maurizi** [comment]
Since it sounds like we haven't had any _android-only_ permissions issues reported since this, I'm closing this for now.
