### ISSUE TITLE
Incorrect password is not reported as such

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-android#201]
We should put up a message that says something akin to "this username or password is incorrect"
![tmp_25106-screenshot_2014-11-02-16-22-15-16425789](https://cloud.githubusercontent.com/assets/4432106/4877280/9832bdf0-62e3-11e4-934c-7a80bdb93ada.png)

**Comment by Rszotak** [comment]
Will be submitting a new message for login failure. Will display "Username or Password Incorrect"
