### ISSUE TITLE
Tree edits won't save on a map that has a custom field with multi-select

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-android#219]
Likely because we don't have #217. I was able to edit a tree on a map that didn't have any multi-select custom fields.

Tested on the latest version of the Android app on an HTC One.

**Comment by maurizi** [comment]
We can also fix this for the current versions of the app server-side by doing https://github.com/OpenTreeMap/otm-core/issues/2235

**Comment by dboyer** [comment]
I tested this on the release server, and I can now edit the tree maps that have multi-select custom fields. However, those fields never appear on the mobile app even when I've selected to display them on mobile. I confirmed the account I was using for testing had permission to edit the multi-select field.

**Comment by dboyer** [comment]
Closing as issue addressed in other Github issues.
