### ISSUE TITLE
OpenTreeMap Android crashes when unit is in Power Save mode

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-android#226]
I have not reproduced this bug, but here is the account from the user:

I believe the android app crashes when the unit is in Power Saver mode.
* I opened the app and tried to login.  It crashed.
* I did it again.  It crashed again.
* I plugged it in to charge it as I noticed the power was low.  Now it works.

Also – each time I opened the app it was asking me to login. Once it is working, it opens up already logged in to my account. I suspect that some system call is failing when the Android device is in Power Saver or Battery Safe mode.

**Comment by maurizi** [comment]
I have not been able to reproduce this either. Closing, and we'll reopen it if it is reported again.
