### ISSUE TITLE
Filter UI doesn't work on all zoom levels for Android tablet Nexus 7

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-android#233]
Using a Nexus 7 tablet and the Android app, I filtered to trees with missing species information on my test map, the aptly named https://www.opentreemap.org/joetestmap.

At first, everything looked good: there are two trees/planting sites that match the criteria "missing species":
![image](https://cloud.githubusercontent.com/assets/12401491/11443080/0baf90dc-94e8-11e5-9d4f-5bd1523fdccb.png)
Zooming in a little further, everything is still working; the two dots are still opaque, although they are a little obscured because the place names layer is on top of the tree dots (one is under the letters "St" in "Franklin St" and the other is under "Science" in "Morehead Planetarium and Science Center"):
![image](https://cloud.githubusercontent.com/assets/12401491/11443028/bdbfe8c2-94e7-11e5-814b-fe0b98f74f10.png)
But beyond that zoom level, the dots disappear altogether—they aren't made semi-transparent as if the filter hasn't caught them, they are just not displayed. Knowing their approximate location, if you click on the map, you can actually select them even though they are invisible, as seen here:
![image](https://cloud.githubusercontent.com/assets/12401491/11443129/69ab68a0-94e8-11e5-90d0-3171bafe8d3a.png)

**Comment by maurizi** [comment]
This was fixed by https://github.com/OpenTreeMap/otm-tiler/issues/101
