### ISSUE TITLE
Filtering Broken Below Certain Zoom Level 

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-android#241]
I filtered down to all "London Plane" trees in Philadelphia
![screenshot_2016-01-19-08-56-22 1](https://cloud.githubusercontent.com/assets/12401491/12420792/a9690cc2-be8c-11e5-9ba3-613f21399b58.png)
You can see the London Plane about a block northwest of my position. However, zooming in just a little bit further makes it disappear:
![screenshot_2016-01-19-08-56-30 1](https://cloud.githubusercontent.com/assets/12401491/12420824/d3a35358-be8c-11e5-8fe0-3fc0ef480491.png)
And clicking on it confirms that it is indeed a London Plane as the first zoom level suggested:
![screenshot_2016-01-19-08-56-53 1](https://cloud.githubusercontent.com/assets/12401491/12420840/e4b13746-be8c-11e5-8489-6169172d7ec8.png)
After clearing the filter, all trees (regardless of species) appeared translucent even though there was no filter being applied.

**Comment by maurizi** [comment]
This probably almost certainly lies with the tiler, see issue https://github.com/OpenTreeMap/otm-tiler/issues/101.

**Comment by maurizi** [comment]
This was fixed by https://github.com/OpenTreeMap/otm-tiler/issues/101
