### ISSUE TITLE
"Add a Picture" vs. "Change a Picture" Button User Feedback

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-android#242]
The text on the button to add a picture should default to "Add a Picture". Only after a photo is added should "Change a Picture" be an option.

Also, since it's possible to add multiple photos, "Add a Picture" should always be an option so that people don't think there can only be one photo at a time.

**Comment by maurizi** [comment]
@jmorrison1847 Have you looked at the latest production version of the android app?  There shouldn't be a button with text anymore, it's moved to a photo icon at the top of the screen.
