### ISSUE TITLE
Clarification of default values and %(packagename)s

### ISSUE THREAD

**Issue by conantp** [OpenTreeMap/otm-android#261]
Hi - I'm working to tie the Android and iOS Apps to a version of the OTM2 code that we have up in running for Asheville, NC. 

When I tried to build the project, I got some errors on the OpenTreeMapSkinned project AndroidManifest.xml file, related to the %(packagename)s and %(versioncode )s variables.

This might be a dumb question, but I'm unfamiliar with where I should be defining those - does that go in the strings.xml resource or somewhere else? 

I'm using Android Studio 1.51 on Mac OS X. 

I was able to hardcode values in there, but then when I run the App, it crashes with a similar issue:

"Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=%(packagename)s/org.azavea.otm.ui.SplashScreenActivity }
Error type 3
Error: Activity class {%(packagename)s/org.azavea.otm.ui.SplashScreenActivity} does not exist."

I think I might be mis-understanding how to setup the "default values" as specified in this readme. 

https://github.com/OpenTreeMap/otm-android/blob/master/OpenTreeMapSkinned/README.md

This line:
"The URLs and and keys needed to run a version of the app, located in an XML file(s) in res/values/:"

Does that mean in the OpenTreeMapSkinned, at res/values/defaults.xml, or somewhere else? 

Any help would be greatly appreciated!

**Comment by maurizi** [comment]
Patrick,

Great to see that you're working on an Android app for Asheville!

You're correct in how to specify your default values, you should create a
file at "OpenTreeMapSkinned/res/values/defaults.xml".  I've attached an
example defaults.xml file (with some values redacted).  In your
defaults.xml file, the "access_key" and "secret_key" values should
match an APIAccessCredential
object that you've created on your server via the
"APIAccessCredential.create" method (
https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/api/models.py#L33-L39
)

For the AndroidManifest.xml, you seem to have it in the right location (at
"OpenTreeMapSkinned/AndroidManifest.xml"), you just need to replace
"%(packagename)s", "%(versioncode)" and "%(versionname)" with a package
name, a machine readable version, and a human readable version respectively.

For example, for the OpenTreeMap application on the Google Play Store, our
package name is "org.azavea.otm2.prod", our current version code is "10"
and our current version name is "1.4.0".

Please send out a link to your app once you get it up onto the Google Play
Store, I've got some friends in Asheville that I'm sure would love to check
it out.

 - Michael

On Thu, Apr 7, 2016 at 7:32 PM Patrick Conant <notifications@github.com>
wrote:

> Hi - I'm working to tie the Android and iOS Apps to a version of the OTM2
> code that we have up in running for Asheville, NC.
>
> When I tried to build the project, I got some errors on the
> OpenTreeMapSkinned project AndroidManifest.xml file, related to the
> %(packagename)s and %(versioncode )s variables.
>
> This might be a dumb question, but I'm unfamiliar with where I should be
> defining those - does that go in the strings.xml resource or somewhere
> else?
>
> I'm using Android Studio 1.51 on Mac OS X.
>
> I was able to hardcode values in there, but then when I run the App, it
> crashes with a similar issue:
>
> "Starting: Intent { act=android.intent.action.MAIN
> cat=[android.intent.category.LAUNCHER]
> cmp=%(packagename)s/org.azavea.otm.ui.SplashScreenActivity }
> Error type 3
> Error: Activity class
> {%(packagename)s/org.azavea.otm.ui.SplashScreenActivity} does not exist."
>
> I think I might be mis-understanding how to setup the "default values" as
> specified in this readme.
>
>
> https://github.com/OpenTreeMap/otm-android/blob/master/OpenTreeMapSkinned/README.md
>
> This line:
> "The URLs and and keys needed to run a version of the app, located in an
> XML file(s) in res/values/:"
>
> Does that mean in the OpenTreeMapSkinned, at res/values/defaults.xml, or
> somewhere else?
>
> Any help would be greatly appreciated!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenTreeMap/otm-android/issues/261>
>
-- 

Michael Maurizi, Software Developer
Azavea |  990 Spring Garden, 5th Floor, Philadelphia, PA
mmaurizi@azavea.com <rcr@azavea.com> | Web azavea.com
<http://www.azavea.com/>  |  @azavea <http://twitter.com/azavea>

**Comment by conantp** [comment]
Michael - thank you so much for your prompt reply. 

OK, so you're saying that %(versioncode )s type strings in the defaults.xml and the manifest are just indicating I should replace those values, correct? I wasn't sure if they were being replaced in the build process some other way, so that makes sense. 

After updating those values, I still had the same issue running the app. But, I then went and updated my build tools version to 23.0.2 in the build.gradle files for OpenTreeMap and OpenTreeMap, which caused Gradle to re-sync. 

That seems to have resolved the issue I was experiencing at launch, and I now have a version of the App up and running! I put garbage values for the configuration (defaults.xml) just to see if I could get it to build, and it worked. 

The developer who set up our server instance has provided me with a secret key and access key, so I'll proceed with the configuration and see if we're good to go! I'll let you know if I get stuck with anything else, but I should be able to work it out from here. 

I don't see the attached defaults.xml you mentioned in your reply above - that might be helpful to me if I encounter any issues, if you're able to post that. 

I can't thank you enough for your help - I'm more experienced with iOS than Android, and a few of those details just threw me off. Seriously, you've saved me so much frustration - if you're ever in Asheville, hit me up and I'll buy you a beer / coffee! 

I'm not sure if you work on the iOS side of things, but I'm having a different set of issues there - I don't know how to get a functioning "base" skin for that version:
https://github.com/OpenTreeMap/otm-ios/issues/294

Patrick Conant

**Comment by maurizi** [comment]
I suspect updating your build tools just caused it to do a clean rebuild of the app, since it does build fine on the current build tools version (incremental compilation can be wonky sometimes).

I guess Github doesn't like attachments or something?
I'll just paste the defaults.xml example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <!-- Instance specific -->
  <string name="app_name">My Map Name</string>
  <string name="skin_code">my_map_name</string>
  <!-- backend specific -->
  <string name="base_url">https://example.com</string>
  <string name="api_url">https://example.com/api/v4</string>
  <string name="tiler_url">https://example.com/tile/</string>
  <string name="access_key">OpenTreeMap_Access_key</string>
  <string name="secret_key">OpenTreeMap_Secret_key</string>
  <!-- build specific -->
  <string name="platform_ver_build">development</string>
  <string name="environment">dev</string>
  <!-- Developer specific -->
  <string name="google_maps_api_key">My_Google_Maps_API_Key</string>
</resources>
```

As for your iOS questions, I can't help much.  In the future, support questions are often better served on our [mailing list](http://groups.google.com/group/opentreemap-user) or our [Gitter channel](https://gitter.im/OpenTreeMap/otm-core?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and you may have better luck reaching out there.

**Comment by maurizi** [comment]
In fact, someone asked on the mailing list about icons already: https://groups.google.com/forum/#!topic/opentreemap-user/QKXau3Mm-p8
