### ISSUE TITLE
When you first open the app it does not take user to current location

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-android#277]
Client reported that the application does not immediate locate user's current location when they log into the Android application. Utah State University (client) recorded the issue via video here: 
https://bft.usu.edu/n8dq3. This link expires after 7 days, but I can repost video if need be.

**Comment by maurizi** [comment]
This was intended behaviour (mimicking what the website does) but it could easily be changed.  @jwalgran what does the iOS app do?

**Comment by jwalgran** [comment]
Since May of 2012 the iOS app has attempted to find the user's location the first time they load e instance map view

https://github.com/OpenTreeMap/otm-ios/commit/f5e145e64fb5cdfe553203ee24a440212c7fd476#diff-4e4a6fb059314ae547aa7ea35b821b8cR90

**Comment by dboyer** [comment]
Let's find the user's location on Android in order to keep functionality similar between the apps whenever possible.

**Comment by hadleystein1** [comment]
Client emailed about this issue again today. Do you have an estimated time to resolution? Not sure whether or not this made it on this sprint. @maurizi

**Comment by maurizi** [comment]
@hadleystein1 This did not make it into this sprint. It would be a relatively simple change though.

**Comment by dboyer** [comment]
@hadleystein1 I added this to the priority backlog. It may make it into the sprint since we're a bit ahead of schedule.
