### ISSUE TITLE
Add Google Analytics code

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-android#281]
just the basics of viewed screens w/ user information.

**Comment by maurizi** [comment]
Some helpful links:
 - General guide https://developers.google.com/analytics/devguides/collection/android/v4/
 - API documentation https://developers.google.com/android/reference/com/google/android/gms/analytics/package-summary
 - Tracking user information https://developers.google.com/analytics/devguides/collection/android/v4/user-id

**Comment by RickMohr** [comment]
Please see [this list of requests](https://github.com/OpenTreeMap/otm-ios/issues/320#issuecomment-253305373) from @kjjustice.

**Comment by maurizi** [comment]
@RickMohr We don't plan on implementing all of the Google Analytics work for Android this sprint - just the basics of viewed screens w/ user information.

We'll be doing the rest in a later issue.
