### ISSUE TITLE
Remove settings that reference cloudfront.net endpoint for tiles

### ISSUE THREAD

**Issue by hectcastro** [OpenTreeMap/otm-android#302]
The `tiler_url` setting includes a direct reference to a `cloudfront.net` domain that is not directly under our control. We should update this reference so that it uses an `opentreemap.org` domain name.

**Comment by maurizi** [comment]
This setting is not defined in the open source code in the Android app, but in a configuration file shared by both the iOS and Android apps (and so it affects the iOS app as well).

I'm closing this issue in favor of https://github.com/OpenTreeMap/otm-mobile-skins/issues/94
