### ISSUE TITLE
Cannot add stewardship activities

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-android#304]
Tested on v47

1. Set stewardship activities to "full write access" for public user role
2. Access map with public user account
3. Add tree with species and diameter
4. Save tree successfully
5. Click back into tree record
6. Select edit
7. Add stewardship activity
8. Click save
9. Receive "cannot save tree" message

**Comment by RobinIsTheBird** [comment]
Confirmed. Added to the Fix Immediate card.
