### ISSUE TITLE
Tree photos not appearing

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-android#307]
This only happens when the apk is connected to AWS, not when connected to a development `otm-cloud`. The suspicion is that the issue is with AWS signed S3 urls. Tree photos do not need the AWS signing, so if that is it, we can just stop signing them.

**Comment by jwalgran** [comment]
If it helps with debugging, we can set up a local development Django app to use the S3 backend. We have a comment in `default_settings.py` that explains how to set that up.

https://github.com/OpenTreeMap/otm-core/blob/77f662725fc4bd3ff15e8a6817f9799757db514f/opentreemap/opentreemap/settings/default_settings.py#L37-L42
